version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:16.0"
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - node/install:
          node-version: "16.0"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # - run:
      #     name: Front-End Testing
      #     command: |
      #       npm run frontend:test
      - run:
          name: API Build
          command: |
            npm run api:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    environment:
      AWS_PROFILE: admin-cli
      AWS_ACCESS_KEY_ID: AKIARWXDPNQE36URGRRM
      AWS_SECRET_ACCESS_KEY: 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
    steps:
      - node/install:
          node-version: "16.0"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Frontend Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: API Deploy
          command: |
            npm run api:deploy
workflows:
  udagram:
    jobs:
      - build
      - deploy
